from typing import TypedDict, List
from BaseClasses import ItemClassification


class ItemDict(TypedDict):
    name: str
    count: int
    classification: ItemClassification


base_id = 2412500


item_table: List[ItemDict] = [
    {"name": "Magnet",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Parry",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Peppermint",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Macaron",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Korsica",
        "count": 1,
        "classification": ItemClassification.progression},

    {"name": "Echo Splash",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Tune Up",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Stomp Box",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Arpeggio Stab",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Pickup Crash",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Harmonic Beam",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Compressor Slam",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Shred",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Staccato Launch",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Gain Tornado",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Quick Beat Hit",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Steal Counter",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Magnet Backstab",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Air Parry",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Directional Parry",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Switch Kicker",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Master Blaster",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Cannon Spike",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Kick Shot",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Double Bass Drop",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "High Strung",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Gravity Well",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Love Tap",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "High Security Risk",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Tornado Lift",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Korsica Typhoon",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "High Alert",
        "count": 1,
        "classification": ItemClassification.useful},

    {"name": "Guitar Ride",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Pick Me Up!",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Pick Slide",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "High Pitch Punch",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Air Guitar",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Rip and Tear",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Double Riff",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Barrier Wall",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Twin Assault",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Steal the Show",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Holo-Chai",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Hibiki!",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Overdrive Slash",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "808-Gigawatt Cat-attack",
        "count": 1,
        "classification": ItemClassification.useful},

    {"name": "Life Gauge",
        "count": 6,
        "classification": ItemClassification.useful},
    {"name": "Electric Reverb Core",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Health Tank",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Additional Chip Slot",
        "count": 4,
        "classification": ItemClassification.useful},
    {"name": "Special Attack Slot Upgrade",
        "count": 1,
        "classification": ItemClassification.useful},

    {"name": "Peppermint Compatibility",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Health Kick",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Battery Magnet",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Rhythm Meter Rush",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Parry Health",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Parry Charge",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Invincible D-Parry",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Damage Rebound D-Parry",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Combo Holder",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Rhythm Dodge Pull Plus",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Rhythm Dodge Pull Cancel",
        "count": 1,
        "classification": ItemClassification.useful},
    {"name": "Peppermint Shock Advantage",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Peppermint Shock Jump",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Macaron Compatibility",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Macaron's Lucky Punch",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Macaron's Aftershock",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Korsica Compatibility",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Super High Alert",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Korsica Stun Extend",
        "count": 3,
        "classification": ItemClassification.useful},
    {"name": "Chip Sense",
        "count": 1,
        "classification": ItemClassification.useful},

    {"name": "Life Gauge Piece",
        "count": 28,
        "classification": ItemClassification.useful},
    {"name": "Electric Reverb Core Piece",
        "count": 12,
        "classification": ItemClassification.useful},
    {"name": "Broken Piece of a Health Tank",
        "count": 10,
        "classification": ItemClassification.useful},
    {"name": "Broken Armstrong Circuit",
        "count": 56,
        "classification": ItemClassification.useful},
    {"name": "Rock Comic (Guitar Ride)",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Rock Comic (Air Guitar)",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Rock Comic (Staccato Launch)",
        "count": 1,
        "classification": ItemClassification.progression},
    {"name": "Rock Comic (Rip and Tear)",
        "count": 1,
        "classification": ItemClassification.progression},

    {"name": "Gears x4,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x5,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x6,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x7,500",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x8,500",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x10,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x12,500",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x15,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x17,500",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x20,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x25,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x30,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x35,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x40,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x45,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x50,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x60,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x65,000",
        "count": 0,
        "classification": ItemClassification.filler},
    {"name": "Gears x80,000",
        "count": 0,
        "classification": ItemClassification.filler},
]