from typing import TypedDict, List


class LocationDict(TypedDict):
    name: str
    region: str
    flag: str


location_table: List[LocationDict] = [
    {"name": "Store - Attacks: Echo Splash",
        "region": "S",
        "flag": "Product::Product.Combos.XYXXX"},
    {"name": "Store - Attacks: Tune Up",
        "region": "S",
        "flag": "Product::Product.Combos.XX-XXX"},
    {"name": "Store - Attacks: Stomp Box",
        "region": "S",
        "flag": "Product::Product.Combos.YXY"},
    {"name": "Store - Attacks: Arpeggio Stab",
        "region": "S",
        "flag": "Product::Product.Combos.XXYYY"},
    {"name": "Store - Attacks: Pickup Crash",
        "region": "S",
        "flag": "Product::Product.Combos.YYX"},
    {"name": "Store - Attacks: Harmonic Beam",
        "region": "S",
        "flag": "Product::Product.Combos.AirXYYY"},
    {"name": "Store - Attacks: Compressor Slam",
        "region": "S",
        "flag": "Product::Product.Combos.AirXYXY"},
    {"name": "Store - Attacks: Shred",
        "region": "S",
        "flag": "Product::Product.Combos.XmY"},
    {"name": "Store - Attacks: Staccato Launch",
        "region": "S",
        "flag": "Product::Product.Combos.C-X"},
    {"name": "Store - Attacks: Gain Tornado",
        "region": "S",
        "flag": "Product::Product.Combos.C-Y"},
    {"name": "Store - Attacks: Quick Beat Hit",
        "region": "S",
        "flag": "Product::Product.Combos.Q-X"},
    {"name": "Store - Attacks: Steal Counter",
        "region": "S",
        "flag": "Product::Product.Combos.Q-Y"},
    {"name": "Store - Attacks: Magnet Backstab",
        "region": "S",
        "flag": "Product::Product.Abilities.MagnetBackstab"},
    {"name": "Store - Attacks: Air Parry",
        "region": "S",
        "flag": "Product::Product.Abilities.AirParry"},
    {"name": "Store - Attacks: Directional Parry",
        "region": "S",
        "flag": "Product::Product.Abilities.DirectionalParry"},
    {"name": "Store - Attacks: Switch Kicker",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.PG01"},
    {"name": "Store - Attacks: Master Blaster",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.PA01"},
    {"name": "Store - Attacks: Cannon Spike",
        "region": "S",
        "flag": "Product::Product.Partners.Charge.P01"},
    {"name": "Store - Attacks: Kick Shot",
        "region": "S",
        "flag": "Product::Product.Partners.Counter.P01"},
    {"name": "Store - Attacks: Double Bass Drop",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.MG01"},
    {"name": "Store - Attacks: High Strung",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.MA01"},
    {"name": "Store - Attacks: Gravity Well",
        "region": "S",
        "flag": "Product::Product.Partners.Charge.M01"},
    {"name": "Store - Attacks: Love Tap",
        "region": "S",
        "flag": "Product::Product.Partners.Counter.M01"},
    {"name": "Store - Attacks: High Security Risk",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.KG01"},
    {"name": "Store - Attacks: Tornado Lift",
        "region": "S",
        "flag": "Product::Product.Partners.JamCombo.KA01"},
    {"name": "Store - Attacks: Korsica Typhoon",
        "region": "S",
        "flag": "Product::Product.Partners.Charge.K01"},
    {"name": "Store - Attacks: High Alert",
        "region": "S",
        "flag": "Product::Product.Partners.Counter.K01"},

    {"name": "Store - Special Attacks: Guitar Ride",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.020"},
    {"name": "Store - Special Attacks: Pick Me Up!",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.030"},
    {"name": "Store - Special Attacks: Pick Slide",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.040"},
    {"name": "Store - Special Attacks: High Pitch Punch",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.050"},
    {"name": "Store - Special Attacks: Air Guitar",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.060"},
    {"name": "Store - Special Attacks: Rip and Tear",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.080"},
    {"name": "Store - Special Attacks: Double Riff",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.310"},
    {"name": "Store - Special Attacks: Barrier Wall",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.330"},
    {"name": "Store - Special Attacks: Twin Assault",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.340"},
    {"name": "Store - Special Attacks: Steal the Show",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.350"},
    {"name": "Store - Special Attacks: Holo-Chai",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.360"},
    {"name": "Store - Special Attacks: Hibiki!",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.610"},
    {"name": "Store - Special Attacks: Overdrive Slash",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.620"},
    {"name": "Store - Special Attacks: 808-Gigawatt Cat-attack",
        "region": "S",
        "flag": "Product::Product.SpecialAttacks.910"},

    # TODO: find a different way to keep track of multiple store items. this isn't gonna work
    {"name": "Store - Items: Life Gauge #1",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp1"},
    {"name": "Store - Items: Life Gauge #2",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp2"},
    {"name": "Store - Items: Life Gauge #3",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp3"},
    {"name": "Store - Items: Life Gauge #4",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp4"},
    {"name": "Store - Items: Life Gauge #5",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp5"},
    {"name": "Store - Items: Life Gauge #6",
        "region": "S",
        "flag": "Product::Product.Items.LifeUp6"},
    {"name": "Store - Items: Electric Reverb Core #1",
        "region": "S",
        "flag": "Product::Product.Items.GaugeUp1"},
    {"name": "Store - Items: Electric Reverb Core #2",
        "region": "S",
        "flag": "Product::Product.Items.GaugeUp2"},
    {"name": "Store - Items: Electric Reverb Core #3",
        "region": "S",
        "flag": "Product::Product.Items.GaugeUp3"},
    {"name": "Store - Items: Health Tank",
        "region": "S",
        "flag": "Product::Product.Items.LifeTank"},
    {"name": "Store - Items: Additional Chip Slot #1",
        "region": "S",
        "flag": "Product::Product.Items.ChipSlot1"},
    {"name": "Store - Items: Additional Chip Slot #2",
        "region": "S",
        "flag": "Product::Product.Items.ChipSlot2"},
    {"name": "Store - Items: Additional Chip Slot #3",
        "region": "S",
        "flag": "Product::Product.Items.ChipSlot3"},
    {"name": "Store - Items: Additional Chip Slot #4",
        "region": "S",
        "flag": "Product::Product.Items.ChipSlot4"},
    {"name": "Store - Items: Special Attack Slot Upgrade",
        "region": "S",
        "flag": "Product::Product.Items.SpAttackSlot"},
    
    {"name": "Store - Chips: Peppermint Compatibility Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeP.Lv1"},
    {"name": "Store - Chips: Peppermint Compatibility Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeP.Lv2"},
    {"name": "Store - Chips: Peppermint Compatibility Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeP.Lv3"},
    {"name": "Store - Chips: Health Kick Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.RecoveryUp.Lv1"},
    {"name": "Store - Chips: Health Kick Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.RecoveryUp.Lv3"},
    {"name": "Store - Chips: Health Kick Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.RecoveryUp.Lv3"},
    {"name": "Store - Chips: Battery Magnet Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.BatteryUp.Lv1"},
    {"name": "Store - Chips: Battery Magnet Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.BatteryUp.Lv2"},
    {"name": "Store - Chips: Battery Magnet Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.BatteryUp.Lv3"},
    {"name": "Store - Chips: Rhythm Meter Rush Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.RhythmMeterUp.Lv1"},
    {"name": "Store - Chips: Rhythm Meter Rush Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.RhythmMeterUp.Lv2"},
    {"name": "Store - Chips: Rhythm Meter Rush Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.RhythmMeterUp.Lv3"},
    {"name": "Store - Chips: Parry Health Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.ParryHealth.Lv1"},
    {"name": "Store - Chips: Parry Health Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.ParryHealth.Lv2"},
    {"name": "Store - Chips: Parry Health Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.ParryHealth.Lv3"},
    {"name": "Store - Chips: Parry Charge Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.ParryBattery.Lv1"},
    {"name": "Store - Chips: Parry Charge Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.ParryBattery.Lv2"},
    {"name": "Store - Chips: Parry Charge Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.ParryBattery.Lv3"},
    {"name": "Store - Chips: Invincible D-Parry Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryInvincible.Lv1"},
    {"name": "Store - Chips: Invincible D-Parry Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryInvincible.Lv2"},
    {"name": "Store - Chips: Invincible D-Parry Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryInvincible.Lv3"},
    {"name": "Store - Chips: Damage Rebound D-Parry Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryDamage.Lv1"},
    {"name": "Store - Chips: Damage Rebound D-Parry Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryDamage.Lv2"},
    {"name": "Store - Chips: Damage Rebound D-Parry Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.DirectionalParryDamage.Lv3"},
    {"name": "Store - Chips: Combo Holder Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.ComboDurationUp.Lv1"},
    {"name": "Store - Chips: Combo Holder Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.ComboDurationUp.Lv2"},
    {"name": "Store - Chips: Combo Holder Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.ComboDurationUp.Lv3"},
    {"name": "Store - Chips: Rhythm Dodge Pull Plus Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.ItemAbsorbUp.Lv1"},
    {"name": "Store - Chips: Rhythm Dodge Pull Plus Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.ItemAbsorbUp.Lv2"},
    {"name": "Store - Chips: Rhythm Dodge Pull Plus Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.ItemAbsorbUp.Lv3"},
    {"name": "Store - Chips: Rhythm Dodge Pull Cancel",
        "region": "S",
        "flag": "Product::Product.Chip.ItemAbsorbCancelInBattle"},
    {"name": "Store - Chips: Peppermint Shock Advantage Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.P_DownTimeUp.Lv1"},
    {"name": "Store - Chips: Peppermint Shock Advantage Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.P_DownTimeUp.Lv2"},
    {"name": "Store - Chips: Peppermint Shock Advantage Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.P_DownTimeUp.Lv3"},
    {"name": "Store - Chips: Peppermint Shock Jump Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.P_ElectricEnemy.Lv1"},
    {"name": "Store - Chips: Peppermint Shock Jump Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.P_ElectricEnemy.Lv2"},
    {"name": "Store - Chips: Peppermint Shock Jump Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.P_ElectricEnemy.Lv3"},
    {"name": "Store - Chips: Macaron Compatibility Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeM.Lv1"},
    {"name": "Store - Chips: Macaron Compatibility Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeM.Lv2"},
    {"name": "Store - Chips: Macaron Compatibility Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeM.Lv3"},
    {"name": "Store - Chips: Macaron's Lucky Punch Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.M_LuckyShieldDamage.Lv1"},
    {"name": "Store - Chips: Macaron's Lucky Punch Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.M_LuckyShieldDamage.Lv2"},
    {"name": "Store - Chips: Macaron's Lucky Punch Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.M_LuckyShieldDamage.Lv3"},
    {"name": "Store - Chips: Macaron's Aftershock Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.M_WaveRangeUp.Lv1"},
    {"name": "Store - Chips: Macaron's Aftershock Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.M_WaveRangeUp.Lv2"},
    {"name": "Store - Chips: Macaron's Aftershock Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.M_WaveRangeUp.Lv3"},
    {"name": "Store - Chips: Korsica Compatibility Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeK.Lv1"},
    {"name": "Store - Chips: Korsica Compatibility Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeK.Lv2"},
    {"name": "Store - Chips: Korsica Compatibility Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.CoolTimeK.Lv3"},
    {"name": "Store - Chips: Super High Alert Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.K_FloatingTimeUp.Lv1"},
    {"name": "Store - Chips: Super High Alert Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.K_FloatingTimeUp.Lv2"},
    {"name": "Store - Chips: Super High Alert Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.K_FloatingTimeUp.Lv3"},
    {"name": "Store - Chips: Korsica Stun Extend Lv.1",
        "region": "S",
        "flag": "Product::Product.Chip.K_DebuffTimeUp.Lv1"},
    {"name": "Store - Chips: Korsica Stun Extend Lv.2",
        "region": "S",
        "flag": "Product::Product.Chip.K_DebuffTimeUp.Lv2"},
    {"name": "Store - Chips: Korsica Stun Extend Lv.3",
        "region": "S",
        "flag": "Product::Product.Chip.K_DebuffTimeUp.Lv3"},
    {"name": "Store - Chips: Chip Sense",
        "region": "S",
        "flag": "Product::Product.Chip.FindingCircuit"},

    {"name": "Track 1: Broken Armstrong Circuit #1",
        "region": "T1",
        "flag": "InventoryItem::St01_RareItemFromSeb"},
    {"name": "Track 1: Life Gauge Piece #1",
        "region": "T1",
        "flag": "InventoryItem::St01_A02_GD_RE_CLifeCoreItem_BP1"},
    {"name": "Track 1: VLog \"TO ALL EMPLOYEES!\"",
        "region": "T1",
        "flag": "InventoryItem::Inventory.File.VLog.0000"},
    {"name": "Track 1: Life Gauge Piece #2",
        "region": "T1",
        "flag": "InventoryItem::St01_A03_GD_RE_CLifeCoreItem_BP2"},
    {"name": "Track 1: SPECTRA Challenge Room",
        "region": "T1",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St01"},
    {"name": "Track 1: VLog \"Battery Pack Production\"",
        "region": "T1",
        "flag": "InventoryItem::Inventory.File.VLog.0010"},
    {"name": "Track 1: VLog \"Old-gen EOL Reminder\"",
        "region": "T1",
        "flag": "InventoryItem::Inventory.File.VLog.0020"},
    {"name": "Track 1: Broken Piece of a Health Tank",
        "region": "T1",
        "flag": "Progress_St01_00::St01_A05_GDnp0600_BP1Item"},
    {"name": "Track 1: Electric Reverb Core Piece",
        "region": "T1",
        "flag": "InventoryItem::St01_A05_GD_CReverbPieceItem_BP_2"},
    {"name": "Track 1: Graffiti #1 (Tower)",
        "region": "T1",
        "flag": "GraffitiCollectFound::Graffiti.Tower"},
    {"name": "Track 1: Broken Armstrong Circuit #2",
        "region": "T1",
        "flag": "Progress_St01_00::St01_A05_2ndPlayRoom_GDnp0600_BP2_2Item"},
    {"name": "Track 1: VLog \"RE:RE:RE:RE:RE:RE:RE: Get on this!\"",
        "region": "T1",
        "flag": "InventoryItem::Inventory.File.VLog.0030"},
    {"name": "Track 1: VLog \"O5-KAR Unit Musings\"",
        "region": "T1",
        "flag": "InventoryItem::Inventory.File.VLog.0040"},
    {"name": "Track 1: Broken Armstrong Circuit #3",
        "region": "T1",
        "flag": "InventoryItem::CircuitItem_BP1"},
    {"name": "Track 1: Graffiti #2 (Crane)",
        "region": "T1",
        "flag": "GraffitiCollectFound::Graffiti.ContainerCrane"},
    {"name": "Track 1: Life Gauge Piece #3",
        "region": "T1",
        "flag": "InventoryItem::St01_QACenterEntrance_GD_CLifeCoreItem_BP3_2"},

    {"name": "Track 2: VLog \"Unsent Complaint\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0050"},
    {"name": "Track 2: Electric Reverb Core Piece #1",
        "region": "T2",
        "flag": "InventoryItem::St02_BattleAeraA_GD_CReverbPieceItem_BP1"},
    {"name": "Track 2: VLog \"HR Auto-Surveillance Recording\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0060"},
    {"name": "Track 2: Unlock Magnet",
        "region": "T2",
        "flag": "Product::Inventory.Ability.Magnet_State"},
    {"name": "Track 2: Broken Armstrong Circuit #1",
        "region": "T2",
        "flag": "InventoryItem::St02_BattleAreaB_GD_CCircuitItem_BP1"},
    {"name": "Track 2: VLog \"HR Claim #324839028555180850195\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0070"},
    {"name": "Track 2: Rock Comic",
        "region": "T2",
        "flag": "InventoryItem::St02_BattleAreaB_GD_CRockComic_A_BP_2"},
    {"name": "Track 2: Broken Armstrong Circuit #2",
        "region": "T2",
        "flag": "InventoryItem::St02_BattleAreaB_GD_CCircuitItem_BP2"},
    {"name": "Track 2: Graffiti #1 (Robot Portrait)",
        "region": "T2",
        "flag": "GraffitiCollectFound::Graffiti.RobotPortrait"},
    {"name": "Track 2: Graffiti #2 (Claw)",
        "region": "T2",
        "flag": "GraffitiCollectFound::Graffiti.CraneGimmick"},
    {"name": "Track 2: Electric Reverb Core Piece #2",
        "region": "T2",
        "flag": "InventoryItem::St02_BattleAreaC_GD_CReverbPieceItem_BP2_5"},
    {"name": "Track 2: Life Gauge Piece #1",
        "region": "T2",
        "flag": "InventoryItem::St02_AreaShowcaseA_GD_CLifeCoreItem_BP3_2"},
    {"name": "Track 2: Broken Armstrong Circuit #3",
        "region": "T2",
        "flag": "Progress_St02_00::St02_AreaPressMachineB_GDnp0600_BP1Item"},
    {"name": "Track 2: Broken Armstrong Circuit #4",
        "region": "T2",
        "flag": "InventoryItem::St02_AreaPressMachineB_GD_CCircuitItem_BP3"},
    {"name": "Track 2: VLog \"Tram Line Issues\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0080"},
    {"name": "Track 2: Unlock Peppermint",
        "region": "T2",
        "flag": "Product::Inventory.Partner.Attack.P01_State"},
    {"name": "Track 2: VLog \"Introducing \"The Arrow!\"\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0090"},
    {"name": "Track 2: SPECTRA Challenge Room",
        "region": "T2",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St02"},
    {"name": "Track 2: Broken Armstrong Circuit #5",
        "region": "T2",
        "flag": "Progress_St02_00::St02_BattleAreaH_GDnp0600_BP2_2Item"},
    {"name": "Track 2: Life Gauge Piece #2",
        "region": "T2",
        "flag": "Progress_St02_00::St02_AreaSteamGimmick_GDnp0600_BP3Item"},
    {"name": "Track 2: Sub-mission (Pigeons scattered!)",
        "region": "T2",
        "flag": "GameFlag::ClearedSubMission_St02"},
    {"name": "Track 2: VLog \"Behind the Showmanship: Sitdown with Rekka\"",
        "region": "T2",
        "flag": "InventoryItem::Inventory.File.VLog.0100"},
    {"name": "Track 2: Graffiti #3 (Rekka)",
        "region": "T2",
        "flag": "GraffitiCollectFound::Graffiti.Rekka"},

    {"name": "Track 3: VLog \"R&D Service Log: Part 1\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0110"},
    {"name": "Track 3: Broken Armstrong Circuit #1",
        "region": "T3",
        "flag": "InventoryItem::St03_Magma01_GD_CCircuitItem_BP1"},
    {"name": "Track 3: Broken Armstrong Circuit #2",
        "region": "T3",
        "flag": "InventoryItem::CircuitItem_BP2"},
    {"name": "Track 3: Broken Piece of a Health Tank",
        "region": "T3",
        "flag": "InventoryItem::LifeTankPieceItem_BP"},
    {"name": "Track 3: Broken Armstrong Circuit #3",
        "region": "T3",
        "flag": "InventoryItem::CircuitItem_BP3"},
    {"name": "Track 3: VLog \"R&D Service Log: Part 2\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0120"},
    {"name": "Track 3: Electric Reverb Core Piece #1",
        "region": "T3",
        "flag": "InventoryItem::ReverbPieceItem_BP2_2"},
    {"name": "Track 3: Graffiti #1 (Flowers)",
        "region": "T3",
        "flag": "GraffitiCollectFound::Graffiti.Flowers"},
    {"name": "Track 3: VLog \"R&D Service Log: Part 3\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0130"},
    {"name": "Track 3: Life Gauge Piece #1",
        "region": "T3",
        "flag": "Progress_St03_00::St03_Magma02_GD_40np0600_BP_2Item"},
    {"name": "Track 3: VLog \"R&D Service Log: Part 4\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0140"},
    {"name": "Track 3: VLog \"Zanzo's Order Request\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0150"},
    {"name": "Track 3: Broken Armstrong Circuit #4",
        "region": "T3",
        "flag": "InventoryItem::St03_Entrance_GD_CCircuitItem_BP5"},
    {"name": "Track 3: Broken Armstrong Circuit #5",
        "region": "T3",
        "flag": "InventoryItem::St03_Entrance_GD_CCircuitItem_BP6"},
    {"name": "Track 3: Graffiti #2 (Volcano)",
        "region": "T3",
        "flag": "GraffitiCollectFound::Graffiti.Volcano"},
    {"name": "Track 3: VLog \"LU-C1LLE Self-Therapy Journal\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0160"},
    {"name": "Track 3: VLog \"Barrier Technology Test Results\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0170"},
    {"name": "Track 3: VLog \"Punch-to-face Test Results\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0180"},
    {"name": "Track 3: Electric Reverb Core Piece #2",
        "region": "T3",
        "flag": "InventoryItem::St03_Labo_GD_CReverbPieceItem_BP_2"},
    {"name": "Track 3: Unlock Parry",
        "region": "T3",
        "flag": "Product::Inventory.Ability.Parry_State"},
    {"name": "Track 3: Broken Armstrong Circuit #6",
        "region": "T3",
        "flag": "InventoryItem::St03_Labo_GD_CCircuitItem_BP4"},
    {"name": "Track 3: VLog \"Offensive Capabilities Test\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0190"},
    {"name": "Track 3: Graffiti #3 (Zanzo)",
        "region": "T3",
        "flag": "GraffitiCollectFound::Graffiti.Zanzo"},
    {"name": "Track 3: VLog \"Barrier Umbrella Test\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0200"},
    {"name": "Track 3: Life Gauge Piece #2",
        "region": "T3",
        "flag": "InventoryItem::St03_Labo_GD_CLifeCoreItem_BP1"},
    {"name": "Track 3: Rock Comic",
        "region": "T3",
        "flag": "InventoryItem::St03_Labo_GD_CRockComic_B_BP_3"},
    {"name": "Track 3: VLog \"Test Lab Assistance Mail\"",
        "region": "T3",
        "flag": "InventoryItem::Inventory.File.VLog.0210"},
    {"name": "Track 3: SPECTRA Challenge Room",
        "region": "T3",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St03"},
    {"name": "Track 3: Life Gauge Piece #3",
        "region": "T3",
        "flag": "InventoryItem::St03_Drill_GD_CLifeCoreItem_BP2_2"},

    {"name": "Track 4: Unlock Macaron",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: VLog \"Staffing Allocation Complaint\"",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #1",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: VLog \"Auto-Saved Private Message\"",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #2",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: VLog \"Disgruntled Decaf Revenge\"",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Piece of a Health Tank #1",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Life Gauge Piece #1",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #3",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Graffiti #1 (HG-0G)",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #4",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: SPECTRA Challenge Room",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Graffiti #2 (VARRT)",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Life Gauge Piece #2",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #5",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Armstrong Circuit #6",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: VLog \"Development Mindfulness Checklist\"",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Broken Piece of a Health Tank #2",
        "region": "T4",
        "flag": ""},
    {"name": "Track 4: Life Gauge Piece #3",
        "region": "T4",
        "flag": ""},

    {"name": "Track 5: Life Gauge Piece #1",
        "region": "T5",
        "flag": "InventoryItem::St05_AIVC_GD_CLifeCoreItem_BP1"},
    {"name": "Track 5: VLog \"Annoyed by Korsica FWD\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0270"},
    {"name": "Track 5: Graffiti #1 (Data Node)",
        "region": "T5",
        "flag": "GraffitiCollectFound::Graffiti.DataSphere"},
    {"name": "Track 5: SPECTRA Challenge Room",
        "region": "T5",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St05"},
    {"name": "Track 5: Broken Armstrong Circuit #1",
        "region": "T5",
        "flag": "InventoryItem::St05_ACS_GD_CCircuitItem_BP1"},
    {"name": "Track 5: Broken Armstrong Circuit #2",
        "region": "T5",
        "flag": "InventoryItem::St05_ACS_GD_CCircuitItem_BP3_2"},
    {"name": "Track 5: VLog \"Musings About Data Node\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0280"},
    {"name": "Track 5: Broken Armstrong Circuit #3",
        "region": "T5",
        "flag": "InventoryItem::St05_ACS_GD_CCircuitItem_BP2_5"},
    {"name": "Track 5: Electric Reverb Core Piece #1",
        "region": "T5",
        "flag": "InventoryItem::St05_AreaA_GD_CReverbPieceItem_BP1"},
    {"name": "Track 5: VLog \"Poem by SCR-UB\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0290"},
    {"name": "Track 5: Rock Comic",
        "region": "T5",
        "flag": "InventoryItem::St05_AreaA_GD_CRockComic_C_BP_2"},
    {"name": "Track 5: VLog \"Vandelay Game Studios?\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0300"},
    {"name": "Track 5: Life Gauge Piece #2",
        "region": "T5",
        "flag": "InventoryItem::LifeCoreItem_BP3_4"},
    {"name": "Track 5: Broken Armstrong Circuit #4",
        "region": "T5",
        "flag": "InventoryItem::St05_ACS_GD_CCircuitItem_BP5_2"},
    {"name": "Track 5: Electric Reverb Core Piece #2",
        "region": "T5",
        "flag": "InventoryItem::ReverbPieceItem_BP2_8"},
    {"name": "Track 5: Broken Armstrong Circuit #5",
        "region": "T5",
        "flag": "InventoryItem::St05_ACSOuter_2ndPlayRoomB_GD_CCircuitItem_BP6_8"},
    {"name": "Track 5: VLog \"Regarding Wing 1 Layout Complaints\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0310"},
    {"name": "Track 5: Broken Armstrong Circuit #6",
        "region": "T5",
        "flag": "InventoryItem::St05_AreaC_GD_CCircuitItem_BP7_5"},
    {"name": "Track 5: Broken Armstrong Circuit #7",
        "region": "T5",
        "flag": "InventoryItem::St05_AreaC_2D_GD_CCircuitItem_BP8_2"},
    {"name": "Track 5: VLog \"FWD: Data Node Advice\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0320"},
    {"name": "Track 5: Broken Armstrong Circuit #8",
        "region": "T5",
        "flag": "InventoryItem::St05_AreaB_GD_CCircuitItem_BP4_12"},
    {"name": "Track 5: VLog \"Korsica Complaints\"",
        "region": "T5",
        "flag": "InventoryItem::Inventory.File.VLog.0330"},
    {"name": "Track 5: Sub-mission (Gathered drone packages!)",
        "region": "T5",
        "flag": "GameFlag::ClearedSubMission_St05"},

    {"name": "Track 6: Broken Armstrong Circuit",
        "region": "T6",
        "flag": "InventoryItem::St05b_AUP_GD_CCircuitItem_BP_2"},
    {"name": "Track 6: Graffiti (L.I.F.T.)",
        "region": "T6",
        "flag": "GraffitiCollectFound::Graffiti.LIFT"},
    {"name": "Track 6: VLog \"L.I.F.T. Construction Heads-up\"",
        "region": "T6",
        "flag": "InventoryItem::Inventory.File.VLog.0340"},

    {"name": "Track 7: VLog \"Platform Construction Note\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0350"},
    {"name": "Track 7: Broken Armstrong Circuit #1",
        "region": "T7",
        "flag": "InventoryItem::St06_Platform_GD_CCircuitItem_BP1"},
    {"name": "Track 7: Broken Armstrong Circuit #2",
        "region": "T7",
        "flag": "InventoryItem::St06_Platform_GD_CCircuitItem_BP2"},
    {"name": "Track 7: Life Gauge Piece #1",
        "region": "T7",
        "flag": "InventoryItem::St06_CylA_GD_CLifeCoreItem_BP1"},
    {"name": "Track 7: Broken Piece of a Health Tank",
        "region": "T7",
        "flag": "InventoryItem::St06_CylA_GD_CLifeTankPieceItem_BP"},
    {"name": "Track 7: Life Gauge Piece #2",
        "region": "T7",
        "flag": "Progress_St06_00::St06_CylA_GDnp0600_BP_2Item"},
    {"name": "Track 7: Electric Reverb Core Piece",
        "region": "T7",
        "flag": "InventoryItem::St06_CylA_GD_CReverbPieceItem_BP_2"},
    {"name": "Track 7: Broken Armstrong Circuit #3",
        "region": "T7",
        "flag": "InventoryItem::St06_CylA_GD_CCircuitItem_BP3_2"},
    {"name": "Track 7: Broken Armstrong Circuit #4",
        "region": "T7",
        "flag": "InventoryItem::St06_CylA_GD_CCircuitItem_BP4"},
    {"name": "Track 7: VLog \"Too Many Rooms\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0360"},
    {"name": "Track 7: Life Gauge Piece #3",
        "region": "T7",
        "flag": "InventoryItem::St06_PassB_GD_CLifeCoreItem_BP2_2"},
    {"name": "Track 7: Broken Armstrong Circuit #5",
        "region": "T7",
        "flag": "InventoryItem::St06_PassB_GD_CCircuitItem_BP5"},
    {"name": "Track 7: SPECTRA Challenge Room",
        "region": "T7",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St06"},
    {"name": "Track 7: VLog \"Suspicious Doors?\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0370"},
    {"name": "Track 7: Rock Comic",
        "region": "T7",
        "flag": "InventoryItem::St06_PassB_GD_CRockComic_D_BP_3"},
    {"name": "Track 7: Broken Armstrong Circuit #6",
        "region": "T7",
        "flag": "InventoryItem::St06_CylB_GD_CCircuitItem_BP6"},
    {"name": "Track 7: VLog \"Data Node Dissatisfaction Mail\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0380"},
    {"name": "Track 7: VLog \"Pmidge Press Announcement\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0390"},
    {"name": "Track 7: Graffiti #1 (Korsica)",
        "region": "T7",
        "flag": "GraffitiCollectFound::Graffiti.Korsica"},
    {"name": "Track 7: Graffiti #2 (KEM-0N0)",
        "region": "T7",
        "flag": "GraffitiCollectFound::Graffiti.Beast"},
    {"name": "Track 7: Broken Armstrong Circuit #7",
        "region": "T7",
        "flag": "InventoryItem::St06_CylB_GD_CCircuitItem_BP7"},
    {"name": "Track 7: VLog \"Depressed Buttons\"",
        "region": "T7",
        "flag": "InventoryItem::Inventory.File.VLog.0400"},
    {"name": "Track 7: Graffiti #3 (Lasers)",
        "region": "T7",
        "flag": "GraffitiCollectFound::Graffiti.Lasers"},
    {"name": "Track 7: Broken Armstrong Circuit #8",
        "region": "T7",
        "flag": "InventoryItem::CircuitItem_BP8"},

    {"name": "Track 8: VLog \"Armstrong Festival Marketing?\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0430"},
    {"name": "Track 8: VLog \"Project Armstrong Raffle Results\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0420"},
    {"name": "Track 8: Sub-mission (Find the golden can!)",
        "region": "T8",
        "flag": "GameFlag::ClearedSubMission_St07"},
    {"name": "Track 8: Broken Armstrong Circuit #1",
        "region": "T8",
        "flag": "InventoryItem::St07_ParkMain_GD_CCircuitItem_BP1"},
    {"name": "Track 8: Graffiti #1 (Fireworks)",
        "region": "T8",
        "flag": "GraffitiCollectFound::Graffiti.Fireworks"},
    {"name": "Track 8: Unlock Korsica",
        "region": "T8",
        "flag": "Product::Inventory.Partner.Attack.K01_State"},
    {"name": "Track 8: Broken Armstrong Circuit #2",
        "region": "T8",
        "flag": "InventoryItem::St07_ParkBR_GD_CCircuitItem_BP2"},
    {"name": "Track 8: VLog \"Charging\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0440"},
    {"name": "Track 8: Broken Piece of a Health Tank #1",
        "region": "T8",
        "flag": "InventoryItem::St07_Constr_GD_CLifeTankPieceItem_BP1"},
    {"name": "Track 8: VLog \"Taking A Break In The Park\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0450"},
    {"name": "Track 8: Electric Reverb Core Piece #1",
        "region": "T8",
        "flag": "InventoryItem::St07_MusExt_GD_CReverbPieceItem_BP1"},
    {"name": "Track 8: Broken Armstrong Circuit #3",
        "region": "T8",
        "flag": "InventoryItem::St07_MusExt_GD_CCircuitItem_BP3"},
    {"name": "Track 8: Graffiti #2 (BL-1Z5)",
        "region": "T8",
        "flag": "GraffitiCollectFound::Graffiti.Blaze"},
    {"name": "Track 8: VLog \"SBR-001 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0490"},
    {"name": "Track 8: VLog \"GNR-020 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0460"},
    {"name": "Track 8: VLog \"ES-101 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0500"},
    {"name": "Track 8: VLog \"BES-102 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0470"},
    {"name": "Track 8: VLog \"BA-B00 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0510"},
    {"name": "Track 8: VLog \"BL-1Z5 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0480"},
    {"name": "Track 8: VLog \"Reminder to Reception\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0520"},
    {"name": "Track 8: VLog \"BRUT-1L Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0530"},
    {"name": "Track 8: VLog \"Our Community Helper: BA-B00\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0540"},
    {"name": "Track 8: VLog \"SEN-C0 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0550"},
    {"name": "Track 8: Graffiti #3 (Stage)",
        "region": "T8",
        "flag": "GraffitiCollectFound::Graffiti.ConcertHall"},
    {"name": "Track 8: Broken Armstrong Circuit #4",
        "region": "T8",
        "flag": "InventoryItem::St07_050_MusInt_History02_GD_CCircuitItem_BP4"},
    {"name": "Track 8: Broken Armstrong Circuit #5",
        "region": "T8",
        "flag": "InventoryItem::St07_060_MusInt_BackRoadA_GD_CCircuitItem_BP5"},
    {"name": "Track 8: Life Gauge Piece #1",
        "region": "T8",
        "flag": "InventoryItem::St07_060_MusInt_BackRoadA_GD_CLifeCoreItem_BP2"},
    {"name": "Track 8: VLog \"Disappointed O5-KAR\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0560"},
    {"name": "Track 8: Broken Piece of a Health Tank #2",
        "region": "T8",
        "flag": "InventoryItem::St07_060_MusInt_BackRoadA_GD_CLifeTankPieceItem_BP2"},
    {"name": "Track 8: VLog \"Water Generator Complaint\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0570"},
    {"name": "Track 8: Electric Reverb Core Piece #2",
        "region": "T8",
        "flag": "InventoryItem::St07_080_MusInt_BigMuseumA_GD_CReverbPieceItem_BP2"},
    {"name": "Track 8: Broken Armstrong Circuit #6",
        "region": "T8",
        "flag": "InventoryItem::St07_080_MusInt_BigMuseumA_GD_CCircuitItem_BP6"},
    {"name": "Track 8: VLog \"Display Complaints\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0580"},
    {"name": "Track 8: Broken Armstrong Circuit #7",
        "region": "T8",
        "flag": "InventoryItem::St07_080_MusInt_BigMuseumA_GD_CCircuitItem_BP7_0"},
    {"name": "Track 8: Life Gauge Piece #2",
        "region": "T8",
        "flag": "InventoryItem::St07_080_MusInt_BigMuseumA_GD_CLifeCoreItem_BP3"},
    {"name": "Track 8: Graffiti #4 (Museum)",
        "region": "T8",
        "flag": "GraffitiCollectFound::Graffiti.Museum"},
    {"name": "Track 8: VLog \"KEM-0N0 Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0590"},
    {"name": "Track 8: VLog \"SBR Development Display\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0600"},
    {"name": "Track 8: Life Gauge Piece #3",
        "region": "T8",
        "flag": "Progress_St07_00::St07_090_MusInt_PoolAreaB_GDnp0600_BP_2Item"},
    {"name": "Track 8: Broken Armstrong Circuit #8",
        "region": "T8",
        "flag": "InventoryItem::St07_090_MusInt_PoolAreaB_GD_CCircuitItem_BP8"},
    {"name": "Track 8: VLog \"Door Musings from SCR-UB\"",
        "region": "T8",
        "flag": "InventoryItem::Inventory.File.VLog.0610"},
    {"name": "Track 8: SPECTRA Challenge Room",
        "region": "T8",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St07"},

    {"name": "Track 9: Graffiti (Mimosa)",
        "region": "T9",
        "flag": "GraffitiCollectFound::Graffiti.Mimosa"},
    {"name": "Track 9: Broken Armstrong Circuit #1",
        "region": "T9",
        "flag": "InventoryItem::St08_Passage_GD_CCircuitItem_BP1"},
    {"name": "Track 9: Life Gauge Piece",
        "region": "T9",
        "flag": "InventoryItem::St08_Passage_GD_CLifeCoreItem_BP_2"},
    {"name": "Track 9: VLog \"Armstrong Festival Briefing Notes\"",
        "region": "T9",
        "flag": "InventoryItem::Inventory.File.VLog.0620"},
    {"name": "Track 9: VLog \"Mimosa's Rider\"",
        "region": "T9",
        "flag": "InventoryItem::Inventory.File.VLog.0630"},
    {"name": "Track 9: Broken Armstrong Circuit #2",
        "region": "T9",
        "flag": "InventoryItem::St08_2DScroll_GD_CCircuitItem_BP2_2"},

    {"name": "Track 10: VLog \"Cafeteria Menu\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0640"},
    {"name": "Track 10: VLog \"Vandelay Grammar Check\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0650"},
    {"name": "Track 10: Graffiti #1 (WA-ES-2)",
        "region": "T10",
        "flag": "GraffitiCollectFound::Graffiti.SAMURAI"},
    {"name": "Track 10: Broken Armstrong Circuit #1",
        "region": "T10",
        "flag": "InventoryItem::St10_030_BranchRoom_GD_CCircuitItem_BP1"},
    {"name": "Track 10: Life Gauge Piece #1",
        "region": "T10",
        "flag": "InventoryItem::St10_040_BackRootA_GD_CLifeCoreItem_BP1"},
    {"name": "Track 10: Broken Armstrong Circuit #2",
        "region": "T10",
        "flag": "InventoryItem::St10_070_TalkRoot_GD_CCircuitItem_BP2"},
    {"name": "Track 10: VLog \"Atrium Statue Mail\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0660"},
    {"name": "Track 10: Broken Armstrong Circuit #3",
        "region": "T10",
        "flag": "InventoryItem::St10_081_Atrium_GD_CCircuitItem_BP3"},
    {"name": "Track 10: Graffiti #2 (Wrench)",
        "region": "T10",
        "flag": "GraffitiCollectFound::Graffiti.Wrench"},
    {"name": "Track 10: Life Gauge Piece #2",
        "region": "T10",
        "flag": "Progress_St10_00::St10_081_Atrium_GDnp0600_BP_6Item"},
    {"name": "Track 10: SPECTRA Challenge Room",
        "region": "T10",
        "flag": "SpectraRoom_Stage::SpectraRoomCleared_St10"},
    {"name": "Track 10: Broken Armstrong Circuit #4",
        "region": "T10",
        "flag": "InventoryItem::St10_083_Atrium_GD_CCircuitItem_BP4"},
    {"name": "Track 10: VLog \"Budget Challenge Mail\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0670"},
    {"name": "Track 10: Life Gauge Piece #3",
        "region": "T10",
        "flag": "InventoryItem::St10_083_Atrium_GD_CLifeCoreItem_BP2"},
    {"name": "Track 10: Broken Armstrong Circuit #5",
        "region": "T10",
        "flag": "InventoryItem::St10_083_Atrium_GD_CCircuitItem_BP5"},
    {"name": "Track 10: VLog \"Hoodie Preorder Mail\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0680"},
    {"name": "Track 10: Broken Piece of a Health Tank",
        "region": "T10",
        "flag": "InventoryItem::St10_083_Atrium_GD_CLifeTankPieceItem_BP_6"},
    {"name": "Track 10: VLog \"Vandelay Handbook Note\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0690"},
    {"name": "Track 10: Graffiti #3 (Roquefort)",
        "region": "T10",
        "flag": "GraffitiCollectFound::Graffiti.Roquefort"},
    {"name": "Track 10: Electric Reverb Core Piece",
        "region": "T10",
        "flag": "InventoryItem::St10_085_Atrium_GD_CReverbPieceItem_BP_2"},
    {"name": "Track 10: Graffiti #4 (Kale)",
        "region": "T10",
        "flag": "GraffitiCollectFound::Graffiti.Kale"},
    {"name": "Track 10: VLog \"Roquefort Meeting Prep\"",
        "region": "T10",
        "flag": "InventoryItem::Inventory.File.VLog.0700"},
    {"name": "Track 10: Broken Armstrong Circuit #6",
        "region": "T10",
        "flag": "InventoryItem::St10_085_Atrium_GD_CCircuitItem_BP6"},
]
